### PR TITLE
OpenAPI 3 support

### PR DESCRIPTION
**Pull request by nmasse-itix**
This PR adds support for OpenAPI 3 since it is now implemented in the 3scale toolbox.

- Added an OpenAPI super-class with two subclasses OpenAPI2 and OpenAPI3
- implements a factory in the `prepareThreescaleService` function

### CODE REVIEW

**Comment by raffamendes** [comment]
Hi,

I have a customer that is very interested in this,  can we commit this into the master?

**Comment by nmasse-itix** [comment]
If nobody has any concerning remark about this PR, I can merge it. Anyone wants to review ?

**Comment by redhatHameed** [comment]
Hi, @nmasse-itix looks good to me. Thanks can you Please merged it I don't have merge access on that.

**Comment by redhatHameed** [comment]
Ping @nmasse-itix

**Comment by nmasse-itix** [comment]
Thanks @redhatHameed your review ! I merged the PR! :)

**Pull request merged**
